spring:
  application:
    name: gestion_sites

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOSTNAME:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
      version: 1.0.0
      description: This is a microservice for managing sites.

# Profiles for different environments
---
spring:
  profiles: dev
  eureka:
    instance:
      hostname: localhost

---
spring:
  profiles: prod
  eureka:
    instance:
      hostname: ${HOSTNAME_ENV}
    client:
      serviceUrl:
        defaultZone: ${EUREKA_PROD_URL}
