version: '3.8'
services:
  gestion-comptes:
    build: .
    ports:
      - "8302:8302"
    depends_on:
      - mysql-service
      - eureka-service
    networks:
      - app-network

  mysql-service:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    networks:
      - app-network

  eureka-service:
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
